<a href="https://colab.research.google.com/github/Baeltor/PCD/blob/prog/NotebooksMLII/Sistemas_de_recomendaci%C3%B3n_II.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <center> <h1> Electiva DSI-II </h1> </center>
___
Presentado por: Sergio David Díaz Veru

Correo: sergio.diaz03@usa.edu.co
___

<center> <h1> Actividad en clase 18/5/23 </h1> </center>

In [ ]:
 pip install scikit-surprise

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
pip install surprise

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import pandas as pd
import numpy as np
from sklearn.metrics import pairwise_distances
from sklearn.preprocessing import MinMaxScaler
from scipy.spatial.distance import cosine
from scipy.stats import pearsonr
import math
from sklearn.metrics.pairwise import cosine_similarity


In [ ]:
df = pd.read_csv('https://www.upgox.io/ai/notebooks/ts/dummy_movies.csv')

In [ ]:
df

userID  itemID  rating
0        1       2       1
1        1       3       4
2        2       1       2
3        2       2       1
4        2       3       2
5        3       1       3
6        3       2       1
7        3       3       4
8        4       1       4
9        4       2       2
10       4       3       1
11       5       1       1
12       5       2       2
13       5       3       3

In [ ]:
!git clone http://github.com/camilousa/recommender.git

fatal: destination path 'recommender' already exists and is not an empty directory.


In [ ]:
df

userID  itemID  rating
0        1       2       1
1        1       3       4
2        2       1       2
3        2       2       1
4        2       3       2
5        3       1       3
6        3       2       1
7        3       3       4
8        4       1       4
9        4       2       2
10       4       3       1
11       5       1       1
12       5       2       2
13       5       3       3

In [ ]:
train = df.drop([6,13])

In [ ]:
train

userID  itemID  rating
0        1       2       1
1        1       3       4
2        2       1       2
3        2       2       1
4        2       3       2
5        3       1       3
7        3       3       4
8        4       1       4
9        4       2       2
10       4       3       1
11       5       1       1
12       5       2       2

In [ ]:
vector_train = to_vector(train)

In [ ]:
vector_train

array([[nan,  1.,  4.],
       [ 2.,  1.,  2.],
       [ 3., nan,  4.],
       [ 4.,  2.,  1.],
       [ 1.,  2., nan]])

In [ ]:
vector_train[[0,1,3], 1:]

array([[1., 4.],
       [1., 2.],
       [2., 1.]])

In [ ]:
cosine_similarity(vector_train[[0,1,3], 1:])

array([[1.        , 0.97618706, 0.65079137],
       [0.97618706, 1.        , 0.8       ],
       [0.65079137, 0.8       , 1.        ]])

* sim(1,2) = 0.97
* sim(1,4) = 0.65

In [ ]:
pred = 2*(0.97)/(0.97+0.65)+4*(0.65)/(0.97+0.65)

In [ ]:
pred

2.802469135802469

In [ ]:
vector_train[[1,3,4]][:, [0,1]]

array([[2., 1.],
       [4., 2.],
       [1., 2.]])

In [ ]:
cosine_similarity(vector_train[[1,3,4]][:, [0,1]])

array([[1. , 1. , 0.8],
       [1. , 1. , 0.8],
       [0.8, 0.8, 1. ]])

In [ ]:
pred_22 = 1*(0.98)/(0.98+0.77)+2*(0.77)/(0.98+0.77)

In [ ]:
pred_22

1.44

In [ ]:
vector_train[[1,2,3]][:, [0,2]]

array([[2., 2.],
       [3., 4.],
       [4., 1.]])

In [ ]:
cosine_similarity(vector_train[[1,2,3]][:, [0,2]])

array([[1.        , 0.98994949, 0.85749293],
       [0.98994949, 1.        , 0.776114  ],
       [0.85749293, 0.776114  , 1.        ]])

In [ ]:
pred_22 = 1*(0.98)/(0.98+0.77)+2*(0.77)/(0.98+0.77)

In [ ]:
pred_22

1.44

In [ ]:
from recommender.utils import to_vector

In [ ]:
vector = to_vector(df)

In [ ]:
vector

array([[nan,  1.,  4.],
       [ 2.,  1.,  2.],
       [ 3.,  1.,  4.],
       [ 4.,  2.,  1.],
       [ 1.,  2.,  3.]])

In [ ]:
vector[:,1:]

array([[1., 4.],
       [1., 2.],
       [1., 4.],
       [2., 1.],
       [2., 3.]])

In [ ]:
pairwise_distances(vector[:,1:])

array([[0.        , 2.        , 0.        , 3.16227766, 1.41421356],
       [2.        , 0.        , 2.        , 1.41421356, 1.41421356],
       [0.        , 2.        , 0.        , 3.16227766, 1.41421356],
       [3.16227766, 1.41421356, 3.16227766, 0.        , 2.        ],
       [1.41421356, 1.41421356, 1.41421356, 2.        , 0.        ]])

In [ ]:
vector[0][0]=3

In [ ]:
vector

array([[3., 1., 4.],
       [2., 1., 2.],
       [3., 1., 4.],
       [4., 2., 1.],
       [1., 2., 3.]])

In [ ]:
1/(pairwise_distances(vector[:,1:])+1)

array([[1.        , 0.33333333, 1.        , 0.24025307, 0.41421356],
       [0.33333333, 1.        , 0.33333333, 0.41421356, 0.41421356],
       [1.        , 0.33333333, 1.        , 0.24025307, 0.41421356],
       [0.24025307, 0.41421356, 0.24025307, 1.        , 0.33333333],
       [0.41421356, 0.41421356, 0.41421356, 0.33333333, 1.        ]])

In [ ]:
3.41/1.41

2.418439716312057

In [ ]:
2*(0.33/(2+0+1.41))+3*(1/(2+0+1.41))+1*(0.41/(2+0+1.41)) ## Errado

1.193548387096774

In [ ]:
2*(0.33/(0.33+1+0.41))+3*(1/(0.33+1+0.41))+1*(0.41/(0.33+1+0.41))

2.339080459770115

## Métricas de similaridad

In [ ]:
math.dist((35,46,157), (18,50,145))

21.18962010041709

In [ ]:
math.dist((35,46,157), (10,12,80))

87.80660567406076

In [ ]:
math.dist((35,18), (18,50))

36.235341863986875

In [ ]:
math.sqrt((35-18)**2+(46-50)**2+(157-145)**2)

21.18962010041709

In [ ]:
p1 = np.array([22, 1500000])
p2 = np.array([30, 1520000])
p3 = np.array([60, 1521000])

In [ ]:
df = pd.DataFrame([p1,p2,p3], columns=['Edad', 'Salario'])

In [ ]:
df

Edad  Salario
0    22  1500000
1    30  1520000
2    60  1521000

In [ ]:
pairwise_distances(df)

array([[    0.        , 20000.0016    , 21000.03438092],
       [20000.0016    ,     0.        ,  1000.4498988 ],
       [21000.03438092,  1000.4498988 ,     0.        ]])

In [ ]:
pairwise_distances(MinMaxScaler().fit_transform(df))

array([[0.        , 0.97537214, 1.41421356],
       [0.97537214, 0.        , 0.79090851],
       [1.41421356, 0.79090851, 0.        ]])

In [ ]:
math.cos(math.pi/4)

0.7071067811865476

In [ ]:
juan = np.array([0.5,0.5])
pedro = np.array([1,0])

In [ ]:
1-cosine(juan,pedro)

0.7071067811865475

In [ ]:
pd.DataFrame([juan,pedro], columns=['Videojuegos', 'Deportes']).corr()

Videojuegos  Deportes
Videojuegos          1.0      -1.0
Deportes            -1.0       1.0

In [ ]:
np.corrcoef(juan,pedro)

/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:2829: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:2830: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]


array([[nan, nan],
       [nan,  1.]])

In [ ]:
juanmov = np.array([3,4,5])
pedromov = np.array([0,1,2])

In [ ]:
1-cosine(juanmov,pedromov)

0.8854377448471461

In [ ]:
np.corrcoef(juanmov,pedromov)

array([[1., 1.],
       [1., 1.]])

In [ ]:
pearsonr(juanmov,pedromov)

PearsonRResult(statistic=0.9999999999999998, pvalue=1.3415758552508148e-08)

## Surprise

In [ ]:
from surprise.prediction_algorithms import KNNBasic
from surprise.dataset import Dataset
from surprise.reader import Reader
from surprise.model_selection import GridSearchCV

In [ ]:
df_train = train.copy()

In [ ]:
df_train

userID  itemID  rating
0        1       2       1
1        1       3       4
2        2       1       2
3        2       2       1
4        2       3       2
5        3       1       3
7        3       3       4
8        4       1       4
9        4       2       2
10       4       3       1
11       5       1       1
12       5       2       2

In [ ]:
data = Dataset.load_from_df(df_train, Reader(rating_scale=(1,5)))

In [ ]:
train = data.build_full_trainset()

In [ ]:
sim_options = {
    'name': 'cosine',
    'user_based': True,
    'min_support':2
}

model = KNNBasic(k=2, sim_options=sim_options)

In [ ]:
model_fit = model.fit(train)

Computing the cosine similarity matrix...
Done computing similarity matrix.


In [ ]:
model_fit.predict(uid=1, iid=1)

Prediction(uid=1, iid=1, r_ui=None, est=2.8, details={'actual_k': 2, 'was_impossible': False})

In [ ]:
model_fit.compute_similarities()

Computing the cosine similarity matrix...
Done computing similarity matrix.


array([[1.        , 0.97618706, 0.        , 0.65079137, 0.        ],
       [0.97618706, 1.        , 0.98994949, 0.87287156, 0.8       ],
       [0.        , 0.98994949, 1.        , 0.776114  , 0.        ],
       [0.65079137, 0.87287156, 0.776114  , 1.        , 0.8       ],
       [0.        , 0.8       , 0.        , 0.8       , 1.        ]])

In [ ]:
train.to_inner_uid(5)

4

In [ ]:
data = Dataset.load_from_df(df_train, Reader(rating_scale=(1,5)))

In [ ]:
param_grid = {
    'k' : [1,2],
    'sim_options': {
        'name': ['msd', 'cosine']
    }
}

In [ ]:
grid_search = GridSearchCV(KNNBasic, cv=3, param_grid=param_grid)

In [ ]:
results = grid_search.fit(data)

Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the cosine similarity matrix...
Done computing similarity matrix.
Computing the cosine similarity matrix...
Done computing similarity matrix.
Computing the cosine similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the cosine similarity matrix...
Done computing similarity matrix.
Computing the cosine similarity matrix...
Done computing similarity matrix.
Computing the cosine similarity matrix...
Done computing similarity matrix.


In [ ]:
grid_search.best_params

{'rmse': {'k': 1, 'sim_options': {'name': 'msd', 'user_based': True}},
 'mae': {'k': 1, 'sim_options': {'name': 'msd', 'user_based': True}}}

In [ ]:
grid_search.best_score

{'rmse': 1.544339660858202, 'mae': 1.375}

In [ ]:
grid_search.cv_results

{'split0_test_rmse': array([1.22474487, 1.22474487, 1.16666667, 1.14564392]),
 'split1_test_rmse': array([2.12132034, 2.39791576, 2.20479276, 2.25      ]),
 'split2_test_rmse': array([1.28695377, 1.28695377, 1.28695377, 1.28695377]),
 'mean_test_rmse': array([1.54433966, 1.63653813, 1.5528044 , 1.5608659 ]),
 'std_test_rmse': array([0.40877664, 0.53897397, 0.46363338, 0.49069439]),
 'rank_test_rmse': array([1, 4, 2, 3]),
 'split0_test_mae': array([1.        , 1.        , 0.91666667, 0.875     ]),
 'split1_test_mae': array([2.        , 2.25      , 2.08333333, 2.125     ]),
 'split2_test_mae': array([1.125, 1.125, 1.125, 1.125]),
 'mean_test_mae': array([1.375     , 1.45833333, 1.375     , 1.375     ]),
 'std_test_mae': array([0.44487826, 0.56211407, 0.50803725, 0.54006172]),
 'rank_test_mae': array([1, 4, 2, 3]),
 'mean_fit_time': array([0.00104189, 0.000573  , 0.00054065, 0.00099055]),
 'std_fit_time': array([0.00027473, 0.00036057, 0.00067778, 0.00131217]),
 'mean_test_time': array([1